export const actionTypes = {
    ADD_TODO: 'ADD_TODO',
    CHECK_TODO: 'CHECK_TODO',
    DELETE_TODO: 'DELETE_TODO',
    EDIT_TODO: 'EDIT_TODO',
    SORT_BY_DATE: 'SORT_BY_DATE',
    SORT_BY_ALPHABET: 'SORT_BY_ALPHABET',
    SORT_BY_ALPHABET_REVERSE: 'SORT_BY_ALPHABET_REVERSE',
};
